### PR TITLE
SM64JS Reanimation!

### PR DESCRIPTION
**Pull request by abnormalhare**
Rise from the dead, sm64js! We will mold you, shape you, we will make you complete!

Cannon cutscene added
camera movement back to mario no longer goes to origin
Area.js, SurfaceLoad.js, ObjectHelpers.js, and ObjBehaviors2.js fully complete and reorganized
BehaviorData somewhat organized
Thwomps, Grindels WIP
WF plank, that one rotating platform, circular rotating platforms, and chuckyas complete
IngameMenu massively added to (~80% complete)
TOTWC progress (need X's level porting tool)
Spawning Star + cutscenes added
mario pausing during cutscenes added (Uncaught why are you calling animation if no animation MY ASS)
many bugs i had caused fixed

### CODE REVIEW

**Comment by abnormalhare** [comment]
still testing pls do not push

**Comment by abnormalhare** [comment]
ok im pretty sure its all good now, tested for a bit, everything works

**Comment by abnormalhare** [comment]
fixed pov shaking camera

**Comment by abnormalhare** [comment]
ok now we're all good, my bad

**Comment by abnormalhare** [comment]
Completed ObjBehaviors2.js & fixed bug i made when completing a level

**Comment by uuphoria2** [comment]
i accidentally clicked revert dont accept it

**Comment by uuphoria2** [comment]
i accidentally clicked revert if it shows up dont accept it

**Pull request merged**
