### PR TITLE
add blj emote for johnny

### PR DESCRIPTION
**Pull request by Cooliokid956**
did i do it right? i noticed the emote system changed

### CODE REVIEW

**Comment by supermariobros575** [comment]
There was no need for this, I messaged snuffy about it already...

**Comment by Cooliokid956** [comment]
oook...

**Comment by supermariobros575** [comment]
You prob should delete is as it wont be needed

**Comment by blueknight64** [comment]
so... no blj emote?

**Comment by blueknight64** [comment]
not noice

**Pull request merged**
