### PR TITLE
PR - Last update to GJ & Dolphin Town

### PR DESCRIPTION
**Pull request by AgentXLP**
This last update gives the minimap a slight update and fixes the OOB in the lake

### CODE REVIEW

**Comment by justabluemouse** [comment]
r/explainlikeimfive

What would be the "GJ," and how'll re-rendering change the mini-map? What exactly do the changes do, in a few words?

**Comment by luphoria** [comment]
> r/explainlikeimfive
> 
> What would be the "GJ," and how'll re-rendering change the mini-map? What exactly do the changes do, in a few words?

fix an oob wall, re-render the minimap

**Comment by luphoria** [comment]
lol x?

**Comment by justabluemouse** [comment]
Still a little confused. What's a GJ, what will re-rendering do to the minimap? Will it enhance the mini-map? Will it do anything at all?

**Comment by justabluemouse** [comment]
And dang, Dolphin Town sounds like it'll be awesome

**Comment by luphoria** [comment]
gj is the internal name for Glider Jungle

**Comment by justabluemouse** [comment]
Anyways, GJ OOB Update, Dolphin Town, and whatever re-rendering is sound like fantastic things to add to the game, hoping this gets added really soon

**Pull request merged**
