### PR TITLE
[WIP] add castle_inside

### PR DESCRIPTION
**Pull request by luphoria**
Ready for merge!

### CODE REVIEW

**Comment by luphoria** [comment]
Fixed merge conflicts

**Comment by luphoria** [comment]
Fixed PSS _mostly._ Still a small issue, however it was traced to /1/10/model.inc.js: the model has different definitions for JP vs other versions. This can be fixed by opening model.inc.c and removing any of the Japanese definitions.
I must have missed one in my fix because there is still a small rendering issue however it now looks much better.

**Comment by luphoria** [comment]
setting back to WIP because I am adding area 2 now, which has an issue with the mirror room (`command.words is undefined` in n64GfxProcessor).
image
You can simply merge commit 4c4a53e and everything will work.

**Comment by smm2mickeyink** [comment]
it looks cool!

**Comment by sm64js** [comment]
merged manually!

**Pull request closed without merging**
