### PR TITLE
Rolling tweaks

### PR DESCRIPTION
**Pull request by Bloxxel64**

### CODE REVIEW

**Comment by Bloxxel64** [comment]
vs code scrwed up on the name lol

**Review by ghost — APPROVED** [review]
This seems like a great add-on to sm64js. Thank you for suggesting it.

**Comment by ImaginaryNeon** [comment]
Wait, rolling? Is it like 3D World's rolling or is it moreso akin to the rolling within Odyssey?

**Comment by Someone567123** [comment]
i think it should be like SMO's rolling, but i don't know if it's possible
to add motion controlls for continous rolling for controller players. (i
should probably help you guys test the motion controlls)

**Comment by AgentXLP** [comment]
> This seems like a great add-on to sm64js. Thank you for suggesting it.

PRing*
He literally made the changes lol

**Comment by ImaginaryNeon** [comment]
> Repository owner deleted a comment from [ImaginaryNeon](https://github.com/ImaginaryNeon) [4 days ago]
Bruh let me talk.

**Pull request merged**
