### PR TITLE
wrong repo

### PR DESCRIPTION
**Pull request by uuphoria**
some faster movement on surface_slow

### CODE REVIEW

**Comment by abnormalhare** [comment]
1. why are you pushing to a legacy version of MMO
2. this is just a preference, not an improvement

**Comment by uuphoria** [comment]
i like the legacy version, it has something special to it and yes it is just a preference, i wasn't intending it to be an improvement

**Comment by uuphoria** [comment]
sorry if there was any confusion!

**Comment by uuphoria** [comment]
oh dang sorry i was trying to push it into my own repo

**Pull request closed without merging**
