### PR TITLE
Added Star door, trap door and door

### PR DESCRIPTION
**Pull request by SMGee4**
You who are reading this, please make sure again there aren't any errors in the console cuz there may be 👉👈.

my fork is a lotta old and I didn't feel like updating it so the scripts are not in their respective folders yet because I don't have those folders 👉👈. I may have forgotten to upload a file too 👉👈

again, the star_door and trap_doors were in castle_inside. The door was in actors.

### CODE REVIEW

**Comment by SMGee4** [comment]
oop I didnt delete these folders in my fork 👉👈

 src/assets.js
src/include/model_ids.js
src/romTextureLoader.js

**Comment by luphoria** [comment]
you need to sync your fork to latest before we can accept it

**Comment by AgentXLP** [comment]
"please make sure again there aren't any errors in the console cuz there may be 👉👈."
So your telling me you didn't test this at all? Test it, make sure it works and fix any errors then recommit if there are any.

**Comment by SMGee4** [comment]
> 
> 
> "please make sure again there aren't any errors in the console cuz there may be 👉👈."
> So your telling me you didn't test this at all? Test it, make sure it works and fix any errors then recommit if there are any.

I did test It just making sure. I have a history of bad luck :(

**Comment by SMGee4** [comment]
Updated my fork

**Comment by 0x2480** [comment]
bruh

**Comment by SMGee4** [comment]
moment

**Comment by 0x2480** [comment]
you are the bruh moment, silence dora :morphomega:

**Comment by 0x2480** [comment]
> Updated my fork

no you didn't, it would have shown up on the fork

**Comment by AgentXLP** [comment]
`ERROR in ./src/include/model_ids.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/agent11/sm64js/src/include/model_ids.js: Identifier 'MODEL_CASTLE_CASTLE_DOOR_UNUSED' has already been declared (35:13)`

**Comment by AgentXLP** [comment]
Yeah, I can see how you bug tested this really good

**Comment by SMGee4** [comment]
oop

**Comment by SMGee4** [comment]
i must have done something rn then. no errors in my console

**Comment by luphoria** [comment]
did you test this at all?? there is no bhv

**Comment by SMGee4** [comment]
bruh what did i do dwvrebrtewevgrthnjunthdbrvc it was X's fault

**Comment by SMGee4** [comment]
> 
> 
> did you test this at all?? there is no bhv

yes door bhv is in special_presets but I didn't add the bhv in yet because it's not necessary at the moment , its just a placeholder

**Comment by luphoria** [comment]
have you actually tested the doors

**Comment by AgentXLP** [comment]
> bruh what did i do dwvrebrtewevgrthnjunthdbrvc it was X's fault

try bug testing next time instead of blaming me :trollface:

**Comment by SMGee4** [comment]
There I've added my missing files, it should work now

**Comment by Cooliokid956** [comment]
> There I've added my missing files, it should work now

did **YOU** test it? :trollface:

**Comment by AgentXLP** [comment]
> > There I've added my missing files, it should work now
> 
> did **YOU** test it? :trollface:

Why trollface flip 😭

**Comment by Cooliokid956** [comment]
> > > There I've added my missing files, it should work now
> > 
> > 
> > did **YOU** test it? :trollface:
> 
> Why trollface flip 😭

idk 😭

**Comment by luphoria** [comment]
Please close this pull, it will not go anywhere

**Comment by SMGee4** [comment]
> There I've added my missing files, it should work now

Would you mind adding this? I said I fixed my conflicting files and directories already 🙂

**Comment by github10omar** [comment]
🏆  yes
winner

**Comment by AgentXLP** [comment]
> > There I've added my missing files, it should work now
> 
> Would you mind adding this? I said I fixed my conflicting files and directories already 🙂

We'll see about that

**Comment by AgentXLP** [comment]
Wow, your code ran perfectly with a record of 3 errors and a failed compile :trollface:

**Pull request closed without merging**
